set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name clk100 [get_ports clk]

set_property PACKAGE_PIN P17 [get_ports {sw[0]}]
set_property PACKAGE_PIN T18 [get_ports {sw[1]}]
set_property PACKAGE_PIN U17 [get_ports {sw[2]}]
set_property PACKAGE_PIN U16 [get_ports {sw[3]}]
set_property PACKAGE_PIN V14 [get_ports {sw[4]}]
set_property PACKAGE_PIN U13 [get_ports {sw[5]}]
set_property PACKAGE_PIN U12 [get_ports {sw[6]}]
set_property PACKAGE_PIN U11 [get_ports {sw[7]}]
set_property PACKAGE_PIN U9  [get_ports {sw[8]}]
set_property PACKAGE_PIN U7  [get_ports {sw[9]}]
set_property PACKAGE_PIN U6  [get_ports {sw[10]}]
set_property PACKAGE_PIN V4  [get_ports {sw[11]}]
set_property PACKAGE_PIN V2  [get_ports {sw[12]}]
set_property PACKAGE_PIN V1  [get_ports {sw[13]}]
set_property PACKAGE_PIN T9  [get_ports {sw[14]}]
set_property PACKAGE_PIN R8  [get_ports {sw[15]}]
set_property PACKAGE_PIN P18 [get_ports {sw[16]}]
set_property PACKAGE_PIN R18 [get_ports {sw[17]}]
set_property PACKAGE_PIN V17 [get_ports {sw[18]}]
set_property PACKAGE_PIN V16 [get_ports {sw[19]}]
set_property PACKAGE_PIN V15 [get_ports {sw[20]}]
set_property PACKAGE_PIN U14 [get_ports {sw[21]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

set_property PACKAGE_PIN D15 [get_ports {btn[0]}]
set_property PACKAGE_PIN C10 [get_ports {btn[1]}]
set_property PACKAGE_PIN C11 [get_ports {btn[2]}]
set_property PACKAGE_PIN H16 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[*]}]

set_property PACKAGE_PIN T14 [get_ports {led[0]}]
set_property PACKAGE_PIN T15 [get_ports {led[1]}]
set_property PACKAGE_PIN R15 [get_ports {led[2]}]
set_property PACKAGE_PIN T16 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

set_property PACKAGE_PIN A6 [get_ports {an[0]}]
set_property PACKAGE_PIN B6 [get_ports {an[1]}]
set_property PACKAGE_PIN A5 [get_ports {an[2]}]
set_property PACKAGE_PIN A4 [get_ports {an[3]}]
set_property PACKAGE_PIN B4 [get_ports {an[4]}]
set_property PACKAGE_PIN A1 [get_ports {an[5]}]
set_property PACKAGE_PIN B2 [get_ports {an[6]}]
set_property PACKAGE_PIN G1 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[*]}]

set_property PACKAGE_PIN E2 [get_ports {seg[0]}]
set_property PACKAGE_PIN A3 [get_ports {seg[1]}]
set_property PACKAGE_PIN B1 [get_ports {seg[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg[4]}]
set_property PACKAGE_PIN D2 [get_ports {seg[5]}]
set_property PACKAGE_PIN B3 [get_ports {seg[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]