set_property IOSTANDARD LVCMOS33 [get_ports {clk100 rst_btn step_btn}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]

set_property PACKAGE_PIN E3 [get_ports clk100]
create_clock -period 10.000 -name clk100 [get_ports clk100]

set_property PACKAGE_PIN D15 [get_ports rst_btn]
set_property PACKAGE_PIN C10 [get_ports step_btn]

set_property PACKAGE_PIN P17 [get_ports {sw[0]}]
set_property PACKAGE_PIN T18 [get_ports {sw[1]}]
set_property PACKAGE_PIN U17 [get_ports {sw[2]}]
set_property PACKAGE_PIN U16 [get_ports {sw[3]}]
set_property PACKAGE_PIN V14 [get_ports {sw[4]}]

set_property PACKAGE_PIN T14 [get_ports {led[0]}]
set_property PACKAGE_PIN T15 [get_ports {led[1]}]
set_property PACKAGE_PIN R15 [get_ports {led[2]}]
set_property PACKAGE_PIN T16 [get_ports {led[3]}]
set_property PACKAGE_PIN R16 [get_ports {led[4]}]
set_property PACKAGE_PIN M16 [get_ports {led[5]}]
set_property PACKAGE_PIN N16 [get_ports {led[6]}]
set_property PACKAGE_PIN N15 [get_ports {led[7]}]
set_property PACKAGE_PIN P15 [get_ports {led[8]}]
set_property PACKAGE_PIN K16 [get_ports {led[9]}]
set_property PACKAGE_PIN L18 [get_ports {led[10]}]
set_property PACKAGE_PIN N17 [get_ports {led[11]}]
set_property PACKAGE_PIN M17 [get_ports {led[12]}]
set_property PACKAGE_PIN M18 [get_ports {led[13]}]
set_property PACKAGE_PIN R17 [get_ports {led[14]}]
set_property PACKAGE_PIN U18 [get_ports {led[15]}]
set_property PACKAGE_PIN V10 [get_ports {led[16]}]
set_property PACKAGE_PIN R7  [get_ports {led[17]}]
set_property PACKAGE_PIN T6  [get_ports {led[18]}]
set_property PACKAGE_PIN R6  [get_ports {led[19]}]
set_property PACKAGE_PIN T5  [get_ports {led[20]}]
set_property PACKAGE_PIN R5  [get_ports {led[21]}]
set_property PACKAGE_PIN T4  [get_ports {led[22]}]
set_property PACKAGE_PIN T3  [get_ports {led[23]}]
set_property PACKAGE_PIN R3  [get_ports {led[24]}]
set_property PACKAGE_PIN P4  [get_ports {led[25]}]
set_property PACKAGE_PIN P3  [get_ports {led[26]}]
set_property PACKAGE_PIN N4  [get_ports {led[27]}]
set_property PACKAGE_PIN M4  [get_ports {led[28]}]
set_property PACKAGE_PIN M3  [get_ports {led[29]}]
set_property PACKAGE_PIN L4  [get_ports {led[30]}]
set_property PACKAGE_PIN L3  [get_ports {led[31]}]
set_property PACKAGE_PIN P14 [get_ports {led[32]}]
set_property PACKAGE_PIN R12 [get_ports {led[33]}]
set_property PACKAGE_PIN T13 [get_ports {led[34]}]
set_property PACKAGE_PIN R13 [get_ports {led[35]}]

set_property PACKAGE_PIN A6 [get_ports {an[0]}]
set_property PACKAGE_PIN B6 [get_ports {an[1]}]
set_property PACKAGE_PIN A5 [get_ports {an[2]}]
set_property PACKAGE_PIN A4 [get_ports {an[3]}]
set_property PACKAGE_PIN B4 [get_ports {an[4]}]
set_property PACKAGE_PIN A1 [get_ports {an[5]}]
set_property PACKAGE_PIN B2 [get_ports {an[6]}]
set_property PACKAGE_PIN G1 [get_ports {an[7]}]

set_property PACKAGE_PIN E2 [get_ports {seg[0]}]
set_property PACKAGE_PIN A3 [get_ports {seg[1]}]
set_property PACKAGE_PIN B1 [get_ports {seg[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg[4]}]
set_property PACKAGE_PIN D2 [get_ports {seg[5]}]
set_property PACKAGE_PIN B3 [get_ports {seg[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg[7]}]