set_property IOSTANDARD LVCMOS33 [get_ports {rst clk clk_A clk_B clk_F}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {which[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]

set_property PACKAGE_PIN E3 [get_ports clk]
create_clock -period 10.000 -name clk100 [get_ports clk]

set_property PACKAGE_PIN D15 [get_ports rst]
set_property PACKAGE_PIN C10 [get_ports clk_A]
set_property PACKAGE_PIN C11 [get_ports clk_B]
set_property PACKAGE_PIN H16 [get_ports clk_F]

create_clock -period 10.000 -name clk100 [get_ports clk]

set_property PACKAGE_PIN P17 [get_ports {data[0]}]
set_property PACKAGE_PIN T18 [get_ports {data[1]}]
set_property PACKAGE_PIN U17 [get_ports {data[2]}]
set_property PACKAGE_PIN U16 [get_ports {data[3]}]
set_property PACKAGE_PIN V14 [get_ports {data[4]}]
set_property PACKAGE_PIN U13 [get_ports {data[5]}]
set_property PACKAGE_PIN U12 [get_ports {data[6]}]
set_property PACKAGE_PIN U11 [get_ports {data[7]}]
set_property PACKAGE_PIN U9  [get_ports {data[8]}]
set_property PACKAGE_PIN U7  [get_ports {data[9]}]
set_property PACKAGE_PIN U6  [get_ports {data[10]}]
set_property PACKAGE_PIN V4  [get_ports {data[11]}]
set_property PACKAGE_PIN V2  [get_ports {data[12]}]
set_property PACKAGE_PIN V1  [get_ports {data[13]}]
set_property PACKAGE_PIN T9  [get_ports {data[14]}]
set_property PACKAGE_PIN R8  [get_ports {data[15]}]
set_property PACKAGE_PIN P18 [get_ports {data[16]}]
set_property PACKAGE_PIN R18 [get_ports {data[17]}]
set_property PACKAGE_PIN V17 [get_ports {data[18]}]
set_property PACKAGE_PIN V16 [get_ports {data[19]}]
set_property PACKAGE_PIN V15 [get_ports {data[20]}]
set_property PACKAGE_PIN U14 [get_ports {data[21]}]
set_property PACKAGE_PIN V12 [get_ports {data[22]}]
set_property PACKAGE_PIN V11 [get_ports {data[23]}]
set_property PACKAGE_PIN V9  [get_ports {data[24]}]
set_property PACKAGE_PIN V7  [get_ports {data[25]}]
set_property PACKAGE_PIN V6  [get_ports {data[26]}]
set_property PACKAGE_PIN V5  [get_ports {data[27]}]
set_property PACKAGE_PIN U3  [get_ports {data[28]}]
set_property PACKAGE_PIN U2  [get_ports {data[29]}]
set_property PACKAGE_PIN U1  [get_ports {data[30]}]
set_property PACKAGE_PIN T8  [get_ports {data[31]}]

set_property PACKAGE_PIN T14 [get_ports {leds[0]}]
set_property PACKAGE_PIN T15 [get_ports {leds[1]}]
set_property PACKAGE_PIN R15 [get_ports {leds[2]}]
set_property PACKAGE_PIN T16 [get_ports {leds[3]}]

set_property PACKAGE_PIN A6 [get_ports {which[0]}]
set_property PACKAGE_PIN B6 [get_ports {which[1]}]
set_property PACKAGE_PIN A5 [get_ports {which[2]}]
set_property PACKAGE_PIN A4 [get_ports {which[3]}]
set_property PACKAGE_PIN B4 [get_ports {which[4]}]
set_property PACKAGE_PIN A1 [get_ports {which[5]}]
set_property PACKAGE_PIN B2 [get_ports {which[6]}]
set_property PACKAGE_PIN G1 [get_ports {which[7]}]

set_property PACKAGE_PIN E2 [get_ports {seg[0]}]
set_property PACKAGE_PIN A3 [get_ports {seg[1]}]
set_property PACKAGE_PIN B1 [get_ports {seg[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg[4]}]
set_property PACKAGE_PIN D2 [get_ports {seg[5]}]
set_property PACKAGE_PIN B3 [get_ports {seg[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg[7]}]